// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace ZestyKitchenHelper.iOS
{
	public partial class LoginViewController : UITableViewController
	{
		public LoginViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
