// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace ZestyKitchenHelper.iOS
{
	public partial class MainViewController : UITableViewController
	{

		public MainViewController (IntPtr handle) : base (handle)
		{
			
		}

        public override void AwakeFromNib()
        {
            base.AwakeFromNib();
        }

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            LoginButton.TouchUpInside += (o, a) =>
            {

            };

            
        }
    }
}
