// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using Auth0.OidcClient;
using System.Threading.Tasks;
using UserNotifications;
using Xamarin.Forms.Platform.iOS;

namespace ZestyKitchenHelper.iOS
{
	public partial class MainPageController : UITableViewController
	{
        private Auth0Client client;
        private UserProfile userProfile;

        public override void AwakeFromNib()
        {
            base.AwakeFromNib();


        }

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

        }

      
        public MainPageController (IntPtr handle) : base (handle)
		{
		}
	}
}
