// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace ZestyKitchenHelper.iOS
{
	public partial class MainPageController : UINavigationItem
	{
		public MainPageController (IntPtr handle) : base (handle)
		{
		}
	}
}
